### ISSUE TITLE
不能用啊，，，

### ISSUE THREAD

**Issue by vrcms** [shadowsocksBak/shadowsocks-php#1]
没有错误提示，，，，

但是也连不上服务器，log里没有内容

需要什么特别的环境吗

我的环境是php5.5+swoole 1.9

**Comment by liaozibo** [comment]
请看你是否启动起来 ps aux | grep php 看看。
另外日志内容在 当前目录 swoole.log 里面。
可以用的哈

**Comment by vrcms** [comment]
有进程滴，，，

就是收不到数据啊，，，怪异，，，

我增加一个onStart的回调函数，加一个echo是可以的。

但是onConnet这个函数开头加echo 都没反应，可见没效果啊。。。

这是什么道理？

**Comment by vrcms** [comment]
我是lnmp 1.3那个环境，不是apache

**Comment by liaozibo** [comment]
这和是不是apache没关系哈，只需要使用php即可。有问题贴日志，不是很清楚你的描述。
